using Rosentis.DomainModel.Base;
using Rosentis.DomainModel.Exceptions;
using Rosentis.DomainModel.Shop;
using System.Collections.Generic;
using System.Linq;

namespace Rosentis.Persistance.Facade
{
	internal class RosentisContextInitializer
	{
		internal static void Seed(RosentisContext context)
		{
			if (!context.Provinces.Any())
			{
				_initProvinces(ref context);
				context.SaveChanges();
			}
			if (!context.ExceptionCategories.Any())
			{
				_initExceptionCategories(ref context);
				context.SaveChanges();
			}
			if (!context.PurchaseTypes.Any())
			{
				_initPurchaseTypes(ref context);
				context.SaveChanges();
			}
		}

		private static void _initPurchaseTypes(ref RosentisContext context)
		{
			IList<PurchaseType> list = new List<PurchaseType>();
			list.Add(new PurchaseType ( "کارت به کارت", null, null, 1 ));
			list.Add(new PurchaseType ("پرداخت در محل", null, null, 2 ));
			foreach (var item in list)
			{
				context.PurchaseTypes.Add(item);
			}
		}
		private static void _initExceptionCategories(ref RosentisContext context)
		{
			IList<ExceptionCategory> list = new List<ExceptionCategory>();
			list.Add(new ExceptionCategory { Id = 1, Title = "ProductCategory" });
			list.Add(new ExceptionCategory { Id = 2, Title = "Brand" });
			list.Add(new ExceptionCategory { Id = 3, Title = "Supplier" });
			list.Add(new ExceptionCategory { Id = 4, Title = "Product" });
			list.Add(new ExceptionCategory { Id = 5, Title = "Messaging" });
			list.Add(new ExceptionCategory { Id = 6, Title = "Authentication" });
			foreach (var item in list)
			{
				context.ExceptionCategories.Add(item);
			}
			_initException(ref list, ref context);
		}

		private static void _initException(ref IList<ExceptionCategory> plist, ref RosentisContext context)
		{
			IList<Exception> list = new List<Exception>();
			list.Add(new Exception { Id = 1, Title = "خطای ورود اطلاعات", Message = "نام دسته بندی وارد شده تکراری می باشد", CategoryId = plist[0].Id });
			list.Add(new Exception { Id = 2, Title = "خطا", Message = "برای دسته بندی ایجاد شده محصول تعریف شده، امکان حذف وجود ندارد", CategoryId = plist[0].Id });
			list.Add(new Exception { Id = 3, Title = "خطا", Message = "دسته بندی مورد نظر دارای زیر مجموعه می باشد، امکان حذف وجود ندارد", CategoryId = plist[0].Id });
			list.Add(new Exception { Id = 4, Title = "خطا", Message = "عنوان برند تکراری", CategoryId = plist[1].Id });
			list.Add(new Exception { Id = 5, Title = "خطا", Message = "برای برند انتخاب شده، یک تا چند محصول موجود می باشد. امکان حذف وجود ندارد", CategoryId = plist[1].Id });
			list.Add(new Exception { Id = 6, Title = "خطا", Message = "تامین کننده ای با این نام در سیستم موجود می باشد", CategoryId = plist[2].Id });
			list.Add(new Exception { Id = 7, Title = "خطا", Message = "محصول تکراری", CategoryId = plist[3].Id });
			list.Add(new Exception { Id = 8, Title = "خطا", Message = "پیام ارسالی خوانده نشده است", CategoryId = plist[5].Id });
			list.Add(new Exception { Id = 100, CategoryId = 6, Message = "اعتبار شما به پایا نرسیده است. لطفا مجددا وارد سیستم شوید", Title = "دسترسی غیر مجاز" });
			list.Add(new Exception { Id = 101, CategoryId = 6, Message = "نام کاربری در دسترس نیست", Title = "دسترسی غیر مجاز" });
			list.Add(new Exception { Id = 102, CategoryId = 6, Message = "کد تایید شما صحیح نمی باشد", Title = "دسترسی غیر مجاز" });
			list.Add(new Exception { Id = 103, CategoryId = 6, Message = "درخواست شما معتبر نیست", Title = "درخواست نامعتبر" });
			list.Add(new Exception { Id = 104, CategoryId = 6, Message = "لطفا با مسئول پشتیبانی تماس حاصل فرمایید", Title = "خطای ناشناس" });
			list.Add(new Exception { Id = 105, CategoryId = 6, Message = "وارد کردن همه فیلدها اجباریست", Title = "خطای اعتبار سنجی" });
			foreach (var item in list)
			{
				context.Exceptions.Add(item);
			}
		}
		private static void _initProvinces(ref RosentisContext context)
		{
			IList<Province> list = new List<Province>();
			list.Add(new Province { Id = 1, Name = "آذربایجان شرقی" });
			list.Add(new Province { Id = 2, Name = "آذربایجان غربی" });
			list.Add(new Province { Id = 3, Name = "اردبیل" });
			list.Add(new Province { Id = 4, Name = "اصفهان" });
			list.Add(new Province { Id = 5, Name = "البرز" });
			list.Add(new Province { Id = 6, Name = "ایلام" });
			list.Add(new Province { Id = 7, Name = "بوشهر" });
			list.Add(new Province { Id = 8, Name = "تهران" });
			list.Add(new Province { Id = 9, Name = "چهارمحال بختیاری" });
			list.Add(new Province { Id = 10, Name = "خراسان جنوبی" });
			list.Add(new Province { Id = 11, Name = "خراسان رضوی" });
			list.Add(new Province { Id = 12, Name = "خراسان شمالی" });
			list.Add(new Province { Id = 13, Name = "خوزستان" });
			list.Add(new Province { Id = 14, Name = "زنجان" });
			list.Add(new Province { Id = 15, Name = "سمنان" });
			list.Add(new Province { Id = 16, Name = "سیستان و بلوچستان" });
			list.Add(new Province { Id = 17, Name = "فارس" });
			list.Add(new Province { Id = 18, Name = "قزوین" });
			list.Add(new Province { Id = 19, Name = "قم" });
			list.Add(new Province { Id = 20, Name = "كردستان" });
			list.Add(new Province { Id = 21, Name = "كرمان" });
			list.Add(new Province { Id = 22, Name = "كرمانشاه" });
			list.Add(new Province { Id = 23, Name = "كهكیلویه و بویراحمد" });
			list.Add(new Province { Id = 24, Name = "گلستان" });
			list.Add(new Province { Id = 25, Name = "گیلان" });
			list.Add(new Province { Id = 26, Name = "لرستان" });
			list.Add(new Province { Id = 27, Name = "مازندران" });
			list.Add(new Province { Id = 28, Name = "مركزی" });
			list.Add(new Province { Id = 29, Name = "هرمزگان" });
			list.Add(new Province { Id = 30, Name = "همدان" });
			list.Add(new Province { Id = 31, Name = "یزد" });
			foreach (var item in list)
			{
				context.Provinces.Add(item);
			}
			_insertCities(ref list, ref context);
		}

		private static void _insertCities(ref IList<Province> plist, ref RosentisContext context)
		{
			IList<City> list = new List<City>();
			list.Add(new City { Id = 1, ProvinceId = plist[0].Id, Name = "آذر شهر" });
			list.Add(new City { Id = 2, ProvinceId = plist[0].Id, Name = "اسكو" });
			list.Add(new City { Id = 3, ProvinceId = plist[0].Id, Name = "اهر" });
			list.Add(new City { Id = 4, ProvinceId = plist[0].Id, Name = "بستان آباد" });
			list.Add(new City { Id = 5, ProvinceId = plist[0].Id, Name = "بناب" });
			list.Add(new City { Id = 6, ProvinceId = plist[0].Id, Name = "بندر شرفخانه" });
			list.Add(new City { Id = 7, ProvinceId = plist[0].Id, Name = "تبریز" });
			list.Add(new City { Id = 8, ProvinceId = plist[0].Id, Name = "تسوج" });
			list.Add(new City { Id = 9, ProvinceId = plist[0].Id, Name = "جلفا" });
			list.Add(new City { Id = 10, ProvinceId = plist[0].Id, Name = "سراب" });
			list.Add(new City { Id = 11, ProvinceId = plist[0].Id, Name = "شبستر" });
			list.Add(new City { Id = 12, ProvinceId = plist[0].Id, Name = "صوفیان" });
			list.Add(new City { Id = 13, ProvinceId = plist[0].Id, Name = "عجبشیر" });
			list.Add(new City { Id = 14, ProvinceId = plist[0].Id, Name = "قره آغاج" });
			list.Add(new City { Id = 15, ProvinceId = plist[0].Id, Name = "كلیبر" });
			list.Add(new City { Id = 16, ProvinceId = plist[0].Id, Name = "كندوان" });
			list.Add(new City { Id = 17, ProvinceId = plist[0].Id, Name = "مراغه" });
			list.Add(new City { Id = 18, ProvinceId = plist[0].Id, Name = "مرند" });
			list.Add(new City { Id = 19, ProvinceId = plist[0].Id, Name = "ملكان" });
			list.Add(new City { Id = 20, ProvinceId = plist[0].Id, Name = "ممقان" });
			list.Add(new City { Id = 21, ProvinceId = plist[0].Id, Name = "میانه" });
			list.Add(new City { Id = 22, ProvinceId = plist[0].Id, Name = "هادیشهر" });
			list.Add(new City { Id = 23, ProvinceId = plist[0].Id, Name = "هریس" });
			list.Add(new City { Id = 24, ProvinceId = plist[0].Id, Name = "هشترود" });
			list.Add(new City { Id = 25, ProvinceId = plist[0].Id, Name = "ورزقان" });
			list.Add(new City { Id = 26, ProvinceId = plist[1].Id, Name = "ارومیه" });
			list.Add(new City { Id = 27, ProvinceId = plist[1].Id, Name = "اشنویه" });
			list.Add(new City { Id = 28, ProvinceId = plist[1].Id, Name = "بازرگان" });
			list.Add(new City { Id = 29, ProvinceId = plist[1].Id, Name = "بوكان" });
			list.Add(new City { Id = 30, ProvinceId = plist[1].Id, Name = "پلدشت" });
			list.Add(new City { Id = 31, ProvinceId = plist[1].Id, Name = "پیرانشهر" });
			list.Add(new City { Id = 32, ProvinceId = plist[1].Id, Name = "تكاب" });
			list.Add(new City { Id = 33, ProvinceId = plist[1].Id, Name = "خوی" });
			list.Add(new City { Id = 34, ProvinceId = plist[1].Id, Name = "سردشت" });
			list.Add(new City { Id = 35, ProvinceId = plist[1].Id, Name = "سلماس" });
			list.Add(new City { Id = 36, ProvinceId = plist[1].Id, Name = "سیه چشمه- چالدران" });
			list.Add(new City { Id = 37, ProvinceId = plist[1].Id, Name = "سیمینه" });
			list.Add(new City { Id = 38, ProvinceId = plist[1].Id, Name = "شاهین دژ" });
			list.Add(new City { Id = 39, ProvinceId = plist[1].Id, Name = "شوط" });
			list.Add(new City { Id = 40, ProvinceId = plist[1].Id, Name = "ماكو" });
			list.Add(new City { Id = 41, ProvinceId = plist[1].Id, Name = "مهاباد" });
			list.Add(new City { Id = 42, ProvinceId = plist[1].Id, Name = "میاندوآب" });
			list.Add(new City { Id = 43, ProvinceId = plist[1].Id, Name = "نقده" });
			list.Add(new City { Id = 44, ProvinceId = plist[2].Id, Name = "اردبیل" });
			list.Add(new City { Id = 45, ProvinceId = plist[2].Id, Name = "بیله سوار" });
			list.Add(new City { Id = 46, ProvinceId = plist[2].Id, Name = "پارس آباد" });
			list.Add(new City { Id = 47, ProvinceId = plist[2].Id, Name = "خلخال" });
			list.Add(new City { Id = 48, ProvinceId = plist[2].Id, Name = "سرعین" });
			list.Add(new City { Id = 49, ProvinceId = plist[2].Id, Name = "كیوی" });
			list.Add(new City { Id = 50, ProvinceId = plist[2].Id, Name = "گرمی" });
			list.Add(new City { Id = 51, ProvinceId = plist[2].Id, Name = "مشگین شهر" });
			list.Add(new City { Id = 52, ProvinceId = plist[2].Id, Name = "مغان" });
			list.Add(new City { Id = 53, ProvinceId = plist[2].Id, Name = "نمین" });
			list.Add(new City { Id = 54, ProvinceId = plist[2].Id, Name = "نیر" });
			list.Add(new City { Id = 55, ProvinceId = plist[3].Id, Name = "آران و بیدگل" });
			list.Add(new City { Id = 56, ProvinceId = plist[3].Id, Name = "اردستان" });
			list.Add(new City { Id = 57, ProvinceId = plist[3].Id, Name = "اصفهان" });
			list.Add(new City { Id = 58, ProvinceId = plist[3].Id, Name = "باغ بهادران" });
			list.Add(new City { Id = 59, ProvinceId = plist[3].Id, Name = "تیران" });
			list.Add(new City { Id = 60, ProvinceId = plist[3].Id, Name = "خمینی شهر" });
			list.Add(new City { Id = 61, ProvinceId = plist[3].Id, Name = "خوانسار" });
			list.Add(new City { Id = 62, ProvinceId = plist[3].Id, Name = "دهاقان" });
			list.Add(new City { Id = 63, ProvinceId = plist[3].Id, Name = "دولت آباد-اصفهان" });
			list.Add(new City { Id = 64, ProvinceId = plist[3].Id, Name = "زرین شهر" });
			list.Add(new City { Id = 65, ProvinceId = plist[3].Id, Name = "زیباشهر" });
			list.Add(new City { Id = 66, ProvinceId = plist[3].Id, Name = "سمیرم" });
			list.Add(new City { Id = 67, ProvinceId = plist[3].Id, Name = "شاهین شهر" });
			list.Add(new City { Id = 68, ProvinceId = plist[3].Id, Name = "شهرضا" });
			list.Add(new City { Id = 69, ProvinceId = plist[3].Id, Name = "فریدن" });
			list.Add(new City { Id = 70, ProvinceId = plist[3].Id, Name = "فریدون شهر" });
			list.Add(new City { Id = 71, ProvinceId = plist[3].Id, Name = "فلاورجان" });
			list.Add(new City { Id = 72, ProvinceId = plist[3].Id, Name = "فولاد شهر" });
			list.Add(new City { Id = 73, ProvinceId = plist[3].Id, Name = "قهدریجان" });
			list.Add(new City { Id = 74, ProvinceId = plist[3].Id, Name = "كاشان" });
			list.Add(new City { Id = 75, ProvinceId = plist[3].Id, Name = "گلپایگان" });
			list.Add(new City { Id = 76, ProvinceId = plist[3].Id, Name = "گلدشت اصفهان" });
			list.Add(new City { Id = 77, ProvinceId = plist[3].Id, Name = "گلدشت مركزی" });
			list.Add(new City { Id = 78, ProvinceId = plist[3].Id, Name = "مباركه اصفهان" });
			list.Add(new City { Id = 79, ProvinceId = plist[3].Id, Name = "مهاباد-اصفهان" });
			list.Add(new City { Id = 80, ProvinceId = plist[3].Id, Name = "نایین" });
			list.Add(new City { Id = 81, ProvinceId = plist[3].Id, Name = "نجف آباد" });
			list.Add(new City { Id = 82, ProvinceId = plist[3].Id, Name = "نطنز" });
			list.Add(new City { Id = 83, ProvinceId = plist[3].Id, Name = "هرند" });
			list.Add(new City { Id = 84, ProvinceId = plist[4].Id, Name = "آسارا" });
			list.Add(new City { Id = 85, ProvinceId = plist[4].Id, Name = "اشتهارد" });
			list.Add(new City { Id = 86, ProvinceId = plist[4].Id, Name = "شهر جدید هشتگرد" });
			list.Add(new City { Id = 87, ProvinceId = plist[4].Id, Name = "طالقان" });
			list.Add(new City { Id = 88, ProvinceId = plist[4].Id, Name = "كرج" });
			list.Add(new City { Id = 89, ProvinceId = plist[4].Id, Name = "گلستان تهران" });
			list.Add(new City { Id = 90, ProvinceId = plist[4].Id, Name = "نظرآباد" });
			list.Add(new City { Id = 91, ProvinceId = plist[4].Id, Name = "هشتگرد" });
			list.Add(new City { Id = 92, ProvinceId = plist[5].Id, Name = "آبدانان" });
			list.Add(new City { Id = 93, ProvinceId = plist[5].Id, Name = "ایلام" });
			list.Add(new City { Id = 94, ProvinceId = plist[5].Id, Name = "ایوان" });
			list.Add(new City { Id = 95, ProvinceId = plist[5].Id, Name = "دره شهر" });
			list.Add(new City { Id = 96, ProvinceId = plist[5].Id, Name = "دهلران" });
			list.Add(new City { Id = 97, ProvinceId = plist[5].Id, Name = "سرابله" });
			list.Add(new City { Id = 98, ProvinceId = plist[5].Id, Name = "شیروان چرداول" });
			list.Add(new City { Id = 99, ProvinceId = plist[5].Id, Name = "مهران" });
			list.Add(new City { Id = 100, ProvinceId = plist[6].Id, Name = "آبپخش" });
			list.Add(new City { Id = 101, ProvinceId = plist[6].Id, Name = "اهرم" });
			list.Add(new City { Id = 102, ProvinceId = plist[6].Id, Name = "برازجان" });
			list.Add(new City { Id = 103, ProvinceId = plist[6].Id, Name = "بندر دیر" });
			list.Add(new City { Id = 104, ProvinceId = plist[6].Id, Name = "بندر دیلم" });
			list.Add(new City { Id = 105, ProvinceId = plist[6].Id, Name = "بندر كنگان" });
			list.Add(new City { Id = 106, ProvinceId = plist[6].Id, Name = "بندر گناوه" });
			list.Add(new City { Id = 107, ProvinceId = plist[6].Id, Name = "بوشهر" });
			list.Add(new City { Id = 108, ProvinceId = plist[6].Id, Name = "تنگستان" });
			list.Add(new City { Id = 109, ProvinceId = plist[6].Id, Name = "جزیره خارك" });
			list.Add(new City { Id = 110, ProvinceId = plist[6].Id, Name = "جم" });
			list.Add(new City { Id = 111, ProvinceId = plist[6].Id, Name = "خورموج" });
			list.Add(new City { Id = 112, ProvinceId = plist[6].Id, Name = "دشتستان - شبانکاره" });
			list.Add(new City { Id = 113, ProvinceId = plist[6].Id, Name = "دلوار" });
			list.Add(new City { Id = 114, ProvinceId = plist[6].Id, Name = "عسلویه" });
			list.Add(new City { Id = 115, ProvinceId = plist[7].Id, Name = "اسلامشهر" });
			list.Add(new City { Id = 116, ProvinceId = plist[7].Id, Name = "بومهن" });
			list.Add(new City { Id = 117, ProvinceId = plist[7].Id, Name = "پاكدشت" });
			list.Add(new City { Id = 118, ProvinceId = plist[7].Id, Name = "تهران" });
			list.Add(new City { Id = 119, ProvinceId = plist[7].Id, Name = "چهاردانگه" });
			list.Add(new City { Id = 120, ProvinceId = plist[7].Id, Name = "دماوند" });
			list.Add(new City { Id = 121, ProvinceId = plist[7].Id, Name = "رودهن" });
			list.Add(new City { Id = 122, ProvinceId = plist[7].Id, Name = "ری" });
			list.Add(new City { Id = 123, ProvinceId = plist[7].Id, Name = "شریف آباد" });
			list.Add(new City { Id = 124, ProvinceId = plist[7].Id, Name = "شهر رباط كریم" });
			list.Add(new City { Id = 125, ProvinceId = plist[7].Id, Name = "شهر شهریار" });
			list.Add(new City { Id = 126, ProvinceId = plist[7].Id, Name = "فشم" });
			list.Add(new City { Id = 127, ProvinceId = plist[7].Id, Name = "فیروزكوه" });
			list.Add(new City { Id = 128, ProvinceId = plist[7].Id, Name = "قدس" });
			list.Add(new City { Id = 129, ProvinceId = plist[7].Id, Name = "كهریزك" });
			list.Add(new City { Id = 130, ProvinceId = plist[7].Id, Name = "لواسان بزرگ" });
			list.Add(new City { Id = 131, ProvinceId = plist[7].Id, Name = "ملارد" });
			list.Add(new City { Id = 132, ProvinceId = plist[7].Id, Name = "ورامین" });
			list.Add(new City { Id = 133, ProvinceId = plist[8].Id, Name = "اردل" });
			list.Add(new City { Id = 134, ProvinceId = plist[8].Id, Name = "بروجن" });
			list.Add(new City { Id = 135, ProvinceId = plist[8].Id, Name = "چلگرد" });
			list.Add(new City { Id = 136, ProvinceId = plist[8].Id, Name = "سامان" });
			list.Add(new City { Id = 137, ProvinceId = plist[8].Id, Name = "شهركرد" });
			list.Add(new City { Id = 138, ProvinceId = plist[8].Id, Name = "فارسان" });
			list.Add(new City { Id = 139, ProvinceId = plist[8].Id, Name = "لردگان" });
			list.Add(new City { Id = 140, ProvinceId = plist[9].Id, Name = "بشرویه" });
			list.Add(new City { Id = 141, ProvinceId = plist[9].Id, Name = "بیرجند" });
			list.Add(new City { Id = 142, ProvinceId = plist[9].Id, Name = "خضری" });
			list.Add(new City { Id = 143, ProvinceId = plist[9].Id, Name = "خوسف" });
			list.Add(new City { Id = 144, ProvinceId = plist[9].Id, Name = "سرایان" });
			list.Add(new City { Id = 145, ProvinceId = plist[9].Id, Name = "سربیشه" });
			list.Add(new City { Id = 146, ProvinceId = plist[9].Id, Name = "طبس" });
			list.Add(new City { Id = 147, ProvinceId = plist[9].Id, Name = "فردوس" });
			list.Add(new City { Id = 148, ProvinceId = plist[9].Id, Name = "قائن" });
			list.Add(new City { Id = 149, ProvinceId = plist[9].Id, Name = "نهبندان" });
			list.Add(new City { Id = 150, ProvinceId = plist[10].Id, Name = "بجستان" });
			list.Add(new City { Id = 151, ProvinceId = plist[10].Id, Name = "بردسكن" });
			list.Add(new City { Id = 152, ProvinceId = plist[10].Id, Name = "تایباد" });
			list.Add(new City { Id = 153, ProvinceId = plist[10].Id, Name = "تربت جام" });
			list.Add(new City { Id = 154, ProvinceId = plist[10].Id, Name = "تربت حیدریه" });
			list.Add(new City { Id = 155, ProvinceId = plist[10].Id, Name = "جغتای" });
			list.Add(new City { Id = 156, ProvinceId = plist[10].Id, Name = "جوین" });
			list.Add(new City { Id = 157, ProvinceId = plist[10].Id, Name = "چناران" });
			list.Add(new City { Id = 158, ProvinceId = plist[10].Id, Name = "خلیل آباد" });
			list.Add(new City { Id = 159, ProvinceId = plist[10].Id, Name = "خواف" });
			list.Add(new City { Id = 160, ProvinceId = plist[10].Id, Name = "درگز" });
			list.Add(new City { Id = 161, ProvinceId = plist[10].Id, Name = "رشتخوار" });
			list.Add(new City { Id = 162, ProvinceId = plist[10].Id, Name = "سبزوار" });
			list.Add(new City { Id = 163, ProvinceId = plist[10].Id, Name = "سرخس" });
			list.Add(new City { Id = 164, ProvinceId = plist[10].Id, Name = "طبس" });
			list.Add(new City { Id = 165, ProvinceId = plist[10].Id, Name = "طرقبه" });
			list.Add(new City { Id = 166, ProvinceId = plist[10].Id, Name = "فریمان" });
			list.Add(new City { Id = 167, ProvinceId = plist[10].Id, Name = "قوچان" });
			list.Add(new City { Id = 168, ProvinceId = plist[10].Id, Name = "كاشمر" });
			list.Add(new City { Id = 169, ProvinceId = plist[10].Id, Name = "كلات" });
			list.Add(new City { Id = 170, ProvinceId = plist[10].Id, Name = "گناباد" });
			list.Add(new City { Id = 171, ProvinceId = plist[10].Id, Name = "مشهد" });
			list.Add(new City { Id = 172, ProvinceId = plist[10].Id, Name = "نیشابور" });
			list.Add(new City { Id = 173, ProvinceId = plist[11].Id, Name = "آشخانه، مانه و سمرقان" });
			list.Add(new City { Id = 174, ProvinceId = plist[11].Id, Name = "اسفراین" });
			list.Add(new City { Id = 175, ProvinceId = plist[11].Id, Name = "بجنورد" });
			list.Add(new City { Id = 176, ProvinceId = plist[11].Id, Name = "جاجرم" });
			list.Add(new City { Id = 177, ProvinceId = plist[11].Id, Name = "شیروان" });
			list.Add(new City { Id = 178, ProvinceId = plist[11].Id, Name = "فاروج" });
			list.Add(new City { Id = 179, ProvinceId = plist[12].Id, Name = "آبادان" });
			list.Add(new City { Id = 180, ProvinceId = plist[12].Id, Name = "امیدیه" });
			list.Add(new City { Id = 181, ProvinceId = plist[12].Id, Name = "اندیمشك" });
			list.Add(new City { Id = 182, ProvinceId = plist[12].Id, Name = "اهواز" });
			list.Add(new City { Id = 183, ProvinceId = plist[12].Id, Name = "ایذه" });
			list.Add(new City { Id = 184, ProvinceId = plist[12].Id, Name = "باغ ملك" });
			list.Add(new City { Id = 185, ProvinceId = plist[12].Id, Name = "بستان" });
			list.Add(new City { Id = 186, ProvinceId = plist[12].Id, Name = "بندر ماهشهر" });
			list.Add(new City { Id = 187, ProvinceId = plist[12].Id, Name = "بندرامام خمینی" });
			list.Add(new City { Id = 188, ProvinceId = plist[12].Id, Name = "بهبهان" });
			list.Add(new City { Id = 189, ProvinceId = plist[12].Id, Name = "خرمشهر" });
			list.Add(new City { Id = 190, ProvinceId = plist[12].Id, Name = "دزفول" });
			list.Add(new City { Id = 191, ProvinceId = plist[12].Id, Name = "رامشیر" });
			list.Add(new City { Id = 192, ProvinceId = plist[12].Id, Name = "رامهرمز" });
			list.Add(new City { Id = 193, ProvinceId = plist[12].Id, Name = "سوسنگرد" });
			list.Add(new City { Id = 194, ProvinceId = plist[12].Id, Name = "شادگان" });
			list.Add(new City { Id = 195, ProvinceId = plist[12].Id, Name = "شوش" });
			list.Add(new City { Id = 196, ProvinceId = plist[12].Id, Name = "شوشتر" });
			list.Add(new City { Id = 197, ProvinceId = plist[12].Id, Name = "لالی" });
			list.Add(new City { Id = 198, ProvinceId = plist[12].Id, Name = "مسجد سلیمان" });
			list.Add(new City { Id = 199, ProvinceId = plist[12].Id, Name = "هندیجان" });
			list.Add(new City { Id = 200, ProvinceId = plist[12].Id, Name = "هویزه" });
			list.Add(new City { Id = 201, ProvinceId = plist[13].Id, Name = "آب بر" });
			list.Add(new City { Id = 202, ProvinceId = plist[13].Id, Name = "ابهر" });
			list.Add(new City { Id = 203, ProvinceId = plist[13].Id, Name = "خرمدره" });
			list.Add(new City { Id = 204, ProvinceId = plist[13].Id, Name = "زرین آباد" });
			list.Add(new City { Id = 205, ProvinceId = plist[13].Id, Name = "زنجان" });
			list.Add(new City { Id = 206, ProvinceId = plist[13].Id, Name = "قیدار" });
			list.Add(new City { Id = 207, ProvinceId = plist[13].Id, Name = "ماهنشان" });
			list.Add(new City { Id = 208, ProvinceId = plist[14].Id, Name = "ایوانكی" });
			list.Add(new City { Id = 209, ProvinceId = plist[14].Id, Name = "بسطام" });
			list.Add(new City { Id = 210, ProvinceId = plist[14].Id, Name = "دامغان" });
			list.Add(new City { Id = 211, ProvinceId = plist[14].Id, Name = "سرخه" });
			list.Add(new City { Id = 212, ProvinceId = plist[14].Id, Name = "سمنان" });
			list.Add(new City { Id = 213, ProvinceId = plist[14].Id, Name = "شاهرود" });
			list.Add(new City { Id = 214, ProvinceId = plist[14].Id, Name = "شهمیرزاد" });
			list.Add(new City { Id = 215, ProvinceId = plist[14].Id, Name = "گرمسار" });
			list.Add(new City { Id = 216, ProvinceId = plist[14].Id, Name = "مهدیشهر" });
			list.Add(new City { Id = 217, ProvinceId = plist[15].Id, Name = "ایرانشهر" });
			list.Add(new City { Id = 218, ProvinceId = plist[15].Id, Name = "چابهار" });
			list.Add(new City { Id = 219, ProvinceId = plist[15].Id, Name = "خاش" });
			list.Add(new City { Id = 220, ProvinceId = plist[15].Id, Name = "راسك" });
			list.Add(new City { Id = 221, ProvinceId = plist[15].Id, Name = "زابل" });
			list.Add(new City { Id = 222, ProvinceId = plist[15].Id, Name = "زاهدان" });
			list.Add(new City { Id = 223, ProvinceId = plist[15].Id, Name = "سراوان" });
			list.Add(new City { Id = 224, ProvinceId = plist[15].Id, Name = "سرباز" });
			list.Add(new City { Id = 225, ProvinceId = plist[15].Id, Name = "میرجاوه" });
			list.Add(new City { Id = 226, ProvinceId = plist[15].Id, Name = "نیكشهر" });
			list.Add(new City { Id = 227, ProvinceId = plist[16].Id, Name = "آباده" });
			list.Add(new City { Id = 228, ProvinceId = plist[16].Id, Name = "آباده طشك" });
			list.Add(new City { Id = 229, ProvinceId = plist[16].Id, Name = "اردكان" });
			list.Add(new City { Id = 230, ProvinceId = plist[16].Id, Name = "ارسنجان" });
			list.Add(new City { Id = 231, ProvinceId = plist[16].Id, Name = "استهبان" });
			list.Add(new City { Id = 232, ProvinceId = plist[16].Id, Name = "اشكنان" });
			list.Add(new City { Id = 233, ProvinceId = plist[16].Id, Name = "اقلید" });
			list.Add(new City { Id = 234, ProvinceId = plist[16].Id, Name = "اوز" });
			list.Add(new City { Id = 235, ProvinceId = plist[16].Id, Name = "ایج" });
			list.Add(new City { Id = 236, ProvinceId = plist[16].Id, Name = "ایزد خواست" });
			list.Add(new City { Id = 237, ProvinceId = plist[16].Id, Name = "باب انار" });
			list.Add(new City { Id = 238, ProvinceId = plist[16].Id, Name = "بالاده" });
			list.Add(new City { Id = 239, ProvinceId = plist[16].Id, Name = "بنارویه" });
			list.Add(new City { Id = 240, ProvinceId = plist[16].Id, Name = "بهمن" });
			list.Add(new City { Id = 241, ProvinceId = plist[16].Id, Name = "بوانات" });
			list.Add(new City { Id = 242, ProvinceId = plist[16].Id, Name = "بیرم" });
			list.Add(new City { Id = 243, ProvinceId = plist[16].Id, Name = "بیضا" });
			list.Add(new City { Id = 244, ProvinceId = plist[16].Id, Name = "جنت شهر" });
			list.Add(new City { Id = 245, ProvinceId = plist[16].Id, Name = "جهرم" });
			list.Add(new City { Id = 246, ProvinceId = plist[16].Id, Name = "حاجی آباد-زرین دشت" });
			list.Add(new City { Id = 247, ProvinceId = plist[16].Id, Name = "خاوران" });
			list.Add(new City { Id = 248, ProvinceId = plist[16].Id, Name = "خرامه" });
			list.Add(new City { Id = 249, ProvinceId = plist[16].Id, Name = "خشت" });
			list.Add(new City { Id = 250, ProvinceId = plist[16].Id, Name = "خفر" });
			list.Add(new City { Id = 251, ProvinceId = plist[16].Id, Name = "خنج" });
			list.Add(new City { Id = 252, ProvinceId = plist[16].Id, Name = "خور" });
			list.Add(new City { Id = 253, ProvinceId = plist[16].Id, Name = "داراب" });
			list.Add(new City { Id = 254, ProvinceId = plist[16].Id, Name = "رونیز علیا" });
			list.Add(new City { Id = 255, ProvinceId = plist[16].Id, Name = "زاهدشهر" });
			list.Add(new City { Id = 256, ProvinceId = plist[16].Id, Name = "زرقان" });
			list.Add(new City { Id = 257, ProvinceId = plist[16].Id, Name = "سده" });
			list.Add(new City { Id = 258, ProvinceId = plist[16].Id, Name = "سروستان" });
			list.Add(new City { Id = 259, ProvinceId = plist[16].Id, Name = "سعادت شهر" });
			list.Add(new City { Id = 260, ProvinceId = plist[16].Id, Name = "سورمق" });
			list.Add(new City { Id = 261, ProvinceId = plist[16].Id, Name = "ششده" });
			list.Add(new City { Id = 262, ProvinceId = plist[16].Id, Name = "شیراز" });
			list.Add(new City { Id = 263, ProvinceId = plist[16].Id, Name = "صغاد" });
			list.Add(new City { Id = 264, ProvinceId = plist[16].Id, Name = "صفاشهر" });
			list.Add(new City { Id = 265, ProvinceId = plist[16].Id, Name = "علاء مرودشت" });
			list.Add(new City { Id = 266, ProvinceId = plist[16].Id, Name = "عنبر" });
			list.Add(new City { Id = 267, ProvinceId = plist[16].Id, Name = "فراشبند" });
			list.Add(new City { Id = 268, ProvinceId = plist[16].Id, Name = "فسا" });
			list.Add(new City { Id = 269, ProvinceId = plist[16].Id, Name = "فیروز آباد" });
			list.Add(new City { Id = 270, ProvinceId = plist[16].Id, Name = "قائمیه" });
			list.Add(new City { Id = 271, ProvinceId = plist[16].Id, Name = "قادر آباد" });
			list.Add(new City { Id = 272, ProvinceId = plist[16].Id, Name = "قطب آباد" });
			list.Add(new City { Id = 273, ProvinceId = plist[16].Id, Name = "قیر" });
			list.Add(new City { Id = 274, ProvinceId = plist[16].Id, Name = "كازرون" });
			list.Add(new City { Id = 275, ProvinceId = plist[16].Id, Name = "كنار تخته" });
			list.Add(new City { Id = 276, ProvinceId = plist[16].Id, Name = "گراش" });
			list.Add(new City { Id = 277, ProvinceId = plist[16].Id, Name = "لار" });
			list.Add(new City { Id = 278, ProvinceId = plist[16].Id, Name = "لامرد" });
			list.Add(new City { Id = 279, ProvinceId = plist[16].Id, Name = "لپوئی" });
			list.Add(new City { Id = 280, ProvinceId = plist[16].Id, Name = "لطیفی" });
			list.Add(new City { Id = 281, ProvinceId = plist[16].Id, Name = "مبارك آباد دیز" });
			list.Add(new City { Id = 282, ProvinceId = plist[16].Id, Name = "مرودشت" });
			list.Add(new City { Id = 283, ProvinceId = plist[16].Id, Name = "مشكان" });
			list.Add(new City { Id = 284, ProvinceId = plist[16].Id, Name = "مصیر" });
			list.Add(new City { Id = 285, ProvinceId = plist[16].Id, Name = "مهر فارس" });
			list.Add(new City { Id = 286, ProvinceId = plist[16].Id, Name = "میمند" });
			list.Add(new City { Id = 287, ProvinceId = plist[16].Id, Name = "نوبندگان" });
			list.Add(new City { Id = 288, ProvinceId = plist[16].Id, Name = "نودان" });
			list.Add(new City { Id = 289, ProvinceId = plist[16].Id, Name = "نورآباد" });
			list.Add(new City { Id = 290, ProvinceId = plist[16].Id, Name = "نی ریز" });
			list.Add(new City { Id = 291, ProvinceId = plist[16].Id, Name = "کوار" });
			list.Add(new City { Id = 292, ProvinceId = plist[17].Id, Name = "آبیك" });
			list.Add(new City { Id = 293, ProvinceId = plist[17].Id, Name = "البرز" });
			list.Add(new City { Id = 294, ProvinceId = plist[17].Id, Name = "بوئین زهرا" });
			list.Add(new City { Id = 295, ProvinceId = plist[17].Id, Name = "تاكستان" });
			list.Add(new City { Id = 296, ProvinceId = plist[17].Id, Name = "قزوین" });
			list.Add(new City { Id = 297, ProvinceId = plist[17].Id, Name = "محمود آباد نمونه" });
			list.Add(new City { Id = 298, ProvinceId = plist[18].Id, Name = "قم" });
			list.Add(new City { Id = 299, ProvinceId = plist[19].Id, Name = "بانه" });
			list.Add(new City { Id = 300, ProvinceId = plist[19].Id, Name = "بیجار" });
			list.Add(new City { Id = 301, ProvinceId = plist[19].Id, Name = "دهگلان" });
			list.Add(new City { Id = 302, ProvinceId = plist[19].Id, Name = "دیواندره" });
			list.Add(new City { Id = 303, ProvinceId = plist[19].Id, Name = "سقز" });
			list.Add(new City { Id = 304, ProvinceId = plist[19].Id, Name = "سنندج" });
			list.Add(new City { Id = 305, ProvinceId = plist[19].Id, Name = "قروه" });
			list.Add(new City { Id = 306, ProvinceId = plist[19].Id, Name = "كامیاران" });
			list.Add(new City { Id = 307, ProvinceId = plist[19].Id, Name = "مریوان" });
			list.Add(new City { Id = 308, ProvinceId = plist[20].Id, Name = "بابك" });
			list.Add(new City { Id = 309, ProvinceId = plist[20].Id, Name = "بافت" });
			list.Add(new City { Id = 310, ProvinceId = plist[20].Id, Name = "بردسیر" });
			list.Add(new City { Id = 311, ProvinceId = plist[20].Id, Name = "بم" });
			list.Add(new City { Id = 312, ProvinceId = plist[20].Id, Name = "جیرفت" });
			list.Add(new City { Id = 313, ProvinceId = plist[20].Id, Name = "راور" });
			list.Add(new City { Id = 314, ProvinceId = plist[20].Id, Name = "رفسنجان" });
			list.Add(new City { Id = 315, ProvinceId = plist[20].Id, Name = "زرند" });
			list.Add(new City { Id = 316, ProvinceId = plist[20].Id, Name = "سیرجان" });
			list.Add(new City { Id = 317, ProvinceId = plist[20].Id, Name = "كرمان" });
			list.Add(new City { Id = 318, ProvinceId = plist[20].Id, Name = "كهنوج" });
			list.Add(new City { Id = 319, ProvinceId = plist[20].Id, Name = "منوجان" });
			list.Add(new City { Id = 320, ProvinceId = plist[21].Id, Name = "اسلام آباد غرب" });
			list.Add(new City { Id = 321, ProvinceId = plist[21].Id, Name = "پاوه" });
			list.Add(new City { Id = 322, ProvinceId = plist[21].Id, Name = "تازه آباد- ثلاث باباجانی" });
			list.Add(new City { Id = 323, ProvinceId = plist[21].Id, Name = "جوانرود" });
			list.Add(new City { Id = 324, ProvinceId = plist[21].Id, Name = "سر پل ذهاب" });
			list.Add(new City { Id = 325, ProvinceId = plist[21].Id, Name = "سنقر كلیائی" });
			list.Add(new City { Id = 326, ProvinceId = plist[21].Id, Name = "صحنه" });
			list.Add(new City { Id = 327, ProvinceId = plist[21].Id, Name = "قصر شیرین" });
			list.Add(new City { Id = 328, ProvinceId = plist[21].Id, Name = "كرمانشاه" });
			list.Add(new City { Id = 329, ProvinceId = plist[21].Id, Name = "كنگاور" });
			list.Add(new City { Id = 330, ProvinceId = plist[21].Id, Name = "گیلان غرب" });
			list.Add(new City { Id = 331, ProvinceId = plist[21].Id, Name = "هرسین" });
			list.Add(new City { Id = 332, ProvinceId = plist[22].Id, Name = "دهدشت" });
			list.Add(new City { Id = 333, ProvinceId = plist[22].Id, Name = "دوگنبدان" });
			list.Add(new City { Id = 334, ProvinceId = plist[22].Id, Name = "سی سخت- دنا" });
			list.Add(new City { Id = 335, ProvinceId = plist[22].Id, Name = "گچساران" });
			list.Add(new City { Id = 336, ProvinceId = plist[22].Id, Name = "یاسوج" });
			list.Add(new City { Id = 337, ProvinceId = plist[23].Id, Name = "آزاد شهر" });
			list.Add(new City { Id = 338, ProvinceId = plist[23].Id, Name = "آق قلا" });
			list.Add(new City { Id = 339, ProvinceId = plist[23].Id, Name = "انبارآلوم" });
			list.Add(new City { Id = 340, ProvinceId = plist[23].Id, Name = "اینچه برون" });
			list.Add(new City { Id = 341, ProvinceId = plist[23].Id, Name = "بندر گز" });
			list.Add(new City { Id = 342, ProvinceId = plist[23].Id, Name = "تركمن" });
			list.Add(new City { Id = 343, ProvinceId = plist[23].Id, Name = "جلین" });
			list.Add(new City { Id = 344, ProvinceId = plist[23].Id, Name = "خان ببین" });
			list.Add(new City { Id = 345, ProvinceId = plist[23].Id, Name = "رامیان" });
			list.Add(new City { Id = 346, ProvinceId = plist[23].Id, Name = "سرخس کلاته" });
			list.Add(new City { Id = 347, ProvinceId = plist[23].Id, Name = "سیمین شهر" });
			list.Add(new City { Id = 348, ProvinceId = plist[23].Id, Name = "علی آباد كتول" });
			list.Add(new City { Id = 349, ProvinceId = plist[23].Id, Name = "فاضل آباد" });
			list.Add(new City { Id = 350, ProvinceId = plist[23].Id, Name = "كردكوی" });
			list.Add(new City { Id = 351, ProvinceId = plist[23].Id, Name = "كلاله" });
			list.Add(new City { Id = 352, ProvinceId = plist[23].Id, Name = "گالیکش" });
			list.Add(new City { Id = 353, ProvinceId = plist[23].Id, Name = "گرگان" });
			list.Add(new City { Id = 354, ProvinceId = plist[23].Id, Name = "گمیش تپه" });
			list.Add(new City { Id = 355, ProvinceId = plist[23].Id, Name = "گنبد كاووس" });
			list.Add(new City { Id = 356, ProvinceId = plist[23].Id, Name = "مراوه تپه" });
			list.Add(new City { Id = 357, ProvinceId = plist[23].Id, Name = "مینو دشت" });
			list.Add(new City { Id = 358, ProvinceId = plist[23].Id, Name = "نگین شهر" });
			list.Add(new City { Id = 359, ProvinceId = plist[23].Id, Name = "نوده خاندوز" });
			list.Add(new City { Id = 360, ProvinceId = plist[23].Id, Name = "نوکنده" });
			list.Add(new City { Id = 361, ProvinceId = plist[24].Id, Name = "آستارا" });
			list.Add(new City { Id = 362, ProvinceId = plist[24].Id, Name = "آستانه اشرفیه" });
			list.Add(new City { Id = 363, ProvinceId = plist[24].Id, Name = "املش" });
			list.Add(new City { Id = 364, ProvinceId = plist[24].Id, Name = "بندرانزلی" });
			list.Add(new City { Id = 365, ProvinceId = plist[24].Id, Name = "خمام" });
			list.Add(new City { Id = 366, ProvinceId = plist[24].Id, Name = "رشت" });
			list.Add(new City { Id = 367, ProvinceId = plist[24].Id, Name = "رضوان شهر" });
			list.Add(new City { Id = 368, ProvinceId = plist[24].Id, Name = "رود سر" });
			list.Add(new City { Id = 369, ProvinceId = plist[24].Id, Name = "رودبار" });
			list.Add(new City { Id = 370, ProvinceId = plist[24].Id, Name = "سیاهكل" });
			list.Add(new City { Id = 371, ProvinceId = plist[24].Id, Name = "شفت" });
			list.Add(new City { Id = 372, ProvinceId = plist[24].Id, Name = "صومعه سرا" });
			list.Add(new City { Id = 373, ProvinceId = plist[24].Id, Name = "فومن" });
			list.Add(new City { Id = 374, ProvinceId = plist[24].Id, Name = "كلاچای" });
			list.Add(new City { Id = 375, ProvinceId = plist[24].Id, Name = "لاهیجان" });
			list.Add(new City { Id = 376, ProvinceId = plist[24].Id, Name = "لنگرود" });
			list.Add(new City { Id = 377, ProvinceId = plist[24].Id, Name = "لوشان" });
			list.Add(new City { Id = 378, ProvinceId = plist[24].Id, Name = "ماسال" });
			list.Add(new City { Id = 379, ProvinceId = plist[24].Id, Name = "ماسوله" });
			list.Add(new City { Id = 380, ProvinceId = plist[24].Id, Name = "منجیل" });
			list.Add(new City { Id = 381, ProvinceId = plist[24].Id, Name = "هشتپر" });
			list.Add(new City { Id = 382, ProvinceId = plist[25].Id, Name = "ازنا" });
			list.Add(new City { Id = 383, ProvinceId = plist[25].Id, Name = "الشتر" });
			list.Add(new City { Id = 384, ProvinceId = plist[25].Id, Name = "الیگودرز" });
			list.Add(new City { Id = 385, ProvinceId = plist[25].Id, Name = "بروجرد" });
			list.Add(new City { Id = 386, ProvinceId = plist[25].Id, Name = "پلدختر" });
			list.Add(new City { Id = 387, ProvinceId = plist[25].Id, Name = "خرم آباد" });
			list.Add(new City { Id = 388, ProvinceId = plist[25].Id, Name = "دورود" });
			list.Add(new City { Id = 389, ProvinceId = plist[25].Id, Name = "سپید دشت" });
			list.Add(new City { Id = 390, ProvinceId = plist[25].Id, Name = "كوهدشت" });
			list.Add(new City { Id = 391, ProvinceId = plist[25].Id, Name = "نورآباد" });
			list.Add(new City { Id = 392, ProvinceId = plist[26].Id, Name = "آمل" });
			list.Add(new City { Id = 393, ProvinceId = plist[26].Id, Name = "بابل" });
			list.Add(new City { Id = 394, ProvinceId = plist[26].Id, Name = "بابلسر" });
			list.Add(new City { Id = 395, ProvinceId = plist[26].Id, Name = "بلده" });
			list.Add(new City { Id = 396, ProvinceId = plist[26].Id, Name = "بهشهر" });
			list.Add(new City { Id = 397, ProvinceId = plist[26].Id, Name = "پل سفید" });
			list.Add(new City { Id = 398, ProvinceId = plist[26].Id, Name = "تنكابن" });
			list.Add(new City { Id = 399, ProvinceId = plist[26].Id, Name = "جویبار" });
			list.Add(new City { Id = 400, ProvinceId = plist[26].Id, Name = "چالوس" });
			list.Add(new City { Id = 401, ProvinceId = plist[26].Id, Name = "خرم آباد" });
			list.Add(new City { Id = 402, ProvinceId = plist[26].Id, Name = "رامسر" });
			list.Add(new City { Id = 403, ProvinceId = plist[26].Id, Name = "رستم کلا" });
			list.Add(new City { Id = 404, ProvinceId = plist[26].Id, Name = "ساری" });
			list.Add(new City { Id = 405, ProvinceId = plist[26].Id, Name = "سلمانشهر" });
			list.Add(new City { Id = 406, ProvinceId = plist[26].Id, Name = "سواد كوه" });
			list.Add(new City { Id = 407, ProvinceId = plist[26].Id, Name = "فریدون كنار" });
			list.Add(new City { Id = 408, ProvinceId = plist[26].Id, Name = "قائم شهر" });
			list.Add(new City { Id = 409, ProvinceId = plist[26].Id, Name = "گلوگاه" });
			list.Add(new City { Id = 410, ProvinceId = plist[26].Id, Name = "محمودآباد" });
			list.Add(new City { Id = 411, ProvinceId = plist[26].Id, Name = "مرزن آباد" });
			list.Add(new City { Id = 412, ProvinceId = plist[26].Id, Name = "نكا" });
			list.Add(new City { Id = 413, ProvinceId = plist[26].Id, Name = "نور" });
			list.Add(new City { Id = 414, ProvinceId = plist[26].Id, Name = "نوشهر" });
			list.Add(new City { Id = 415, ProvinceId = plist[27].Id, Name = "آشتیان" });
			list.Add(new City { Id = 416, ProvinceId = plist[27].Id, Name = "اراك" });
			list.Add(new City { Id = 417, ProvinceId = plist[27].Id, Name = "تفرش" });
			list.Add(new City { Id = 418, ProvinceId = plist[27].Id, Name = "خمین" });
			list.Add(new City { Id = 419, ProvinceId = plist[27].Id, Name = "دلیجان" });
			list.Add(new City { Id = 420, ProvinceId = plist[27].Id, Name = "ساوه" });
			list.Add(new City { Id = 421, ProvinceId = plist[27].Id, Name = "شازند" });
			list.Add(new City { Id = 422, ProvinceId = plist[27].Id, Name = "محلات" });
			list.Add(new City { Id = 423, ProvinceId = plist[27].Id, Name = "کمیجان" });
			list.Add(new City { Id = 424, ProvinceId = plist[28].Id, Name = "ابوموسی" });
			list.Add(new City { Id = 425, ProvinceId = plist[28].Id, Name = "انگهران" });
			list.Add(new City { Id = 426, ProvinceId = plist[28].Id, Name = "بستك" });
			list.Add(new City { Id = 427, ProvinceId = plist[28].Id, Name = "بندر جاسك" });
			list.Add(new City { Id = 428, ProvinceId = plist[28].Id, Name = "بندر لنگه" });
			list.Add(new City { Id = 429, ProvinceId = plist[28].Id, Name = "بندرعباس" });
			list.Add(new City { Id = 430, ProvinceId = plist[28].Id, Name = "پارسیان" });
			list.Add(new City { Id = 431, ProvinceId = plist[28].Id, Name = "حاجی آباد" });
			list.Add(new City { Id = 432, ProvinceId = plist[28].Id, Name = "دشتی" });
			list.Add(new City { Id = 433, ProvinceId = plist[28].Id, Name = "دهبارز" });
			list.Add(new City { Id = 434, ProvinceId = plist[28].Id, Name = "قشم" });
			list.Add(new City { Id = 435, ProvinceId = plist[28].Id, Name = "كیش" });
			list.Add(new City { Id = 436, ProvinceId = plist[28].Id, Name = "میناب" });
			list.Add(new City { Id = 437, ProvinceId = plist[29].Id, Name = "اسدآباد" });
			list.Add(new City { Id = 438, ProvinceId = plist[29].Id, Name = "بهار" });
			list.Add(new City { Id = 439, ProvinceId = plist[29].Id, Name = "تویسركان" });
			list.Add(new City { Id = 440, ProvinceId = plist[29].Id, Name = "رزن" });
			list.Add(new City { Id = 441, ProvinceId = plist[29].Id, Name = "كبودر اهنگ" });
			list.Add(new City { Id = 442, ProvinceId = plist[29].Id, Name = "ملایر" });
			list.Add(new City { Id = 443, ProvinceId = plist[29].Id, Name = "نهاوند" });
			list.Add(new City { Id = 444, ProvinceId = plist[29].Id, Name = "همدان" });
			list.Add(new City { Id = 445, ProvinceId = plist[30].Id, Name = "ابركوه" });
			list.Add(new City { Id = 446, ProvinceId = plist[30].Id, Name = "اردكان" });
			list.Add(new City { Id = 447, ProvinceId = plist[30].Id, Name = "اشكذر" });
			list.Add(new City { Id = 448, ProvinceId = plist[30].Id, Name = "بافق" });
			list.Add(new City { Id = 449, ProvinceId = plist[30].Id, Name = "تفت" });
			list.Add(new City { Id = 450, ProvinceId = plist[30].Id, Name = "مهریز" });
			list.Add(new City { Id = 451, ProvinceId = plist[30].Id, Name = "میبد" });
			list.Add(new City { Id = 452, ProvinceId = plist[30].Id, Name = "هرات" });
			list.Add(new City { Id = 453, ProvinceId = plist[30].Id, Name = "یزد" });
			list.Add(new City { Id = 2140, ProvinceId = plist[12].Id, Name = "کارون" });
			foreach (var item in list)
			{
				context.Cities.Add(item);
			}
		}
	}
}