// <auto-generated />
namespace Rosentis.Persistance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removemapofparent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removemapofparent));
        
        string IMigrationMetadata.Id
        {
            get { return "202005020458597_remove-map-of-parent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
